#variables:
# GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#stages:
# - build
# - test
# - sonarqube-check
#build:
# stage: build
# script:
#  - ./gradlew assemble
#test:
# stage: test
# script:
#  - ./gradlew test
#
#
#sonarqube-check:
# stage: sonarqube-check
# script: ./gradlew test sonar
# allow_failure: true
# only:
#  - master

variables:
 GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
 - build
 - test
 - sonarqube-check

build:
 stage: build
 script:
  - gradle assemble

test:
 stage: test
 script:
  - gradle test

sonarqube-check:
 stage: sonarqube-check
 script:
  - gradle test sonarqube
 allow_failure: true
 only:
  - master

