image: docker:latest

stages:
 - build
 - test
 - sonar

variables:
 DOCKER_IMAGE_TAG: latest

services:
 - docker:dind

before_script:
 - docker info

build:
 stage: build
 script:
  - docker build -t myapp:$CI_COMMIT_SHORT_SHA .

test:
 stage: test
 script:
  - docker run myapp:$CI_COMMIT_SHORT_SHA ./gradlew test

sonar:
 stage: sonar
 script:
  - docker run myapp:$CI_COMMIT_SHORT_SHA ./gradlew test sonar
 allow_failure: true  # Optional: Allow the pipeline to succeed even if SonarQube analysis fails

