#variables:
# GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#stages:
# - build
# - test
# - sonarqube-check
#build:
# stage: build
# script:
#  - ./gradlew assemble
#test:
# stage: test
# script:
#  - ./gradlew test
#
#
#sonarqube-check:
# stage: sonarqube-check
# script: ./gradlew test sonar
# allow_failure: true
# only:
#  - master

before_script:
 - chmod +x gradlew
 - java -version

variables:
 GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"

stages:
 - build
 - test
 - sonarqube-check

build:
 stage: build
 script:
  - export JAVA_HOME="C:\\Program Files\\Java\\jdk-17"
  - export PATH="$JAVA_HOME/bin:$PATH"
  - ./gradlew assemble

test:
 stage: test
 script:
  - ./gradlew test

sonarqube-check:
 stage: sonarqube-check
 script:
  - ./gradlew test sonarqube
 allow_failure: true
 only:
  - master

cache:
 paths:
  - ~/.gradle/caches
  - ~/.gradle/wrapper

