#variables:
# GRADLE_OPTS: "-Dorg.gradle.daemon=false"
#
#stages:
# - build
# - test
# - sonarqube-check
#build:
# stage: build
# script:
#  - ./gradlew assemble
#test:
# stage: test
# script:
#  - ./gradlew test
#
#
#sonarqube-check:
# stage: sonarqube-check
# script: ./gradlew test sonar
# allow_failure: true
# only:
#  - master

before_script:
 - chmod +x gradlew
 - export SPRING_PROFILES_ACTIVE=production


variables:
 GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true"
 MYSQL_DATABASE: "huister"
 MYSQL_ROOT_PASSWORD: "root"

services:
 - name: mysql:8.0
stages:
 - build
 - test
 - sonarqube-check

build:
 stage: build
 script:
  - ./gradlew assemble

test:
 stage: test
 script:
  - ./gradlew test --scan

sonarqube-check:
 stage: sonarqube-check
 script:
  - ./gradlew test sonarqube
 allow_failure: true
 only:
  - master

cache:
 paths:
  - ~/.gradle/caches
  - ~/.gradle/wrapper

