variables:
 GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
 - build
 - test
 - jacoco
 - sonarqube-check

build:
 stage: build
 script:
  - ./gradlew assemble

test:
 stage: test
 script:
  - ./gradlew test

sonarqube-check:
 stage: sonarqube-check
 script:
  - ./gradlew test sonar

#sonarqube-check:
# stage: sonarqube-check
# image: gradle:8.2.0-jdk17-jammy
# variables:
#  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
#  GIT_DEPTH: "0"
# cache:
#  key: "${CI_JOB_NAME}"
#  paths:
#   - .sonar/cache
# script:
#  - ./gradlew test sonar
# allow_failure: true
# only:
#  - merge_requests
#  - master
#  - main
#  - develop