version: "3"
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: 'huister'
      MYSQL_USER: 'calvin'
      MYSQL_PASSWORD: 'kwan'
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  spring-app:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties
      - ./src/main/resources/application-prod.properties:/app/src/main/resources/application-prod.properties
    depends_on:
      - mysql

volumes:
  mysql-data:
