@startuml

'Controller Layer

Class UserController{
    'properties
    UserUseCasesCollection userUseCasesCollection

    'Methods
    ResponseEntity<GetUserByIdResponse> getUserById()
    ResponseEntity<Void> createUser(CreateUserRequest request)
    ResponseEntity<Void> updateUser(long id, UpdateUserRequest request)
    ResponseEntity<LoginResponse> login(LoginRequest request)
    ResponseEntity<Void> changePassword(long id, ChangePasswordRequest request)
    ResponseEntity<List<GetAllOwnersResponse>> getAllOwners()
    ResponseEntity<Void> setProfilePictureUrl(long id, SetProfilePictureUrlRequest request)
}

UserUseCasesCollection <-- UserController

'Business Layer

'User UseCases
Interface UserUseCasesCollection{
    GetUserByIdResponse getUserById()
    Void createUser(CreateUserRequest request)
    Void updateUser(UpdateUserRequest request)
    LoginResponse login(LoginRequest request)
    Void changePassword(LoginRequest request)
    List<GetAllOwnersResponse> getAllOwners()
    Void setProfilePictureUrl(setProfilePictureUrlRequest request)}
}

Class UserUseCasesCollectionImpl{
    'Property
    UserRepository userRepository

    'Method
    GetUserByIdResponse getUserById()
    Void createUser(CreateUserRequest request)
    Void updateUser(UpdateUserRequest request)
    LoginResponse login(LoginRequest request)
    Void changePassword(LoginRequest request)
    List<GetAllOwnersResponse> getAllOwners()
    Void setProfilePictureUrl(setProfilePictureUrlRequest request)
}

UserUseCasesCollection <|.. UserUseCasesCollectionImpl

UserRepository <-- UserUseCasesCollectionImpl

UserEntity <-- UserUseCasesCollectionImpl

'Repository
Interface UserRepository

'Entities

Enum UserRole{
    ADMIN
    OWNER
    CUSTOMER
}

UserRole *-- UserEntity

Class UserEntity{
    long id
    String username
    String password
    String name
    String email
    String phoneNumber
    String profilePictureUrl
    UserRole role
    boolean isActivated
}

@enduml