@startuml

'Controller Layer


Class CityController{
    'properties
    CityUseCase cityUseCase

    'Methods
    ResponseEntity<GetAllCitiesResponse> getAllCities(long id)
}

CityUseCase <-- CityController

'Business Layer

'City UseCases
Interface CityUseCase{
    GetAllCitiesResponse getAllCities(long id)
}

Class CityUseCaseImpl{
    'Property
    CityRepository cityRepository

    'Method
    GetAllCitiesResponse getAllCities(long id)
}

CityUseCase <|.. CityUseCaseImpl

CityRepository <-- CityUseCaseImpl

CityEntity <-- CityUseCaseImpl

'Repository
Interface CityRepository

'Entities

Class CityEntity{
    long id
    String name
}

CityEntity --> CityRepository

@enduml